update:
	wget -q -O fedora-rawhide.config https://src.fedoraproject.org/rpms/kernel/raw/rawhide/f/kernel-ppc64le-fedora.config
	wget -q -O opensuse.config https://github.com/openSUSE/kernel-source/raw/master/config/ppc64le/default
