#!/bin/bash
#
# $ make corenet64_smp_defconfig
# $ make guest.config
# $ echo CONFIG_E6500_CPU=y >> .config
# $ make olddefconfig

exec "$(dirname "$0")"/qemu-ppc64e --cpu e6500 --cloud-image debian-sid-powerpc.qcow2 "$@"
