#!/usr/bin/python3
#
# $ cd ~/src/linux
# $ make
# $ ~/src/ci-scripts/scripts/boot/qemu-44x

import logging
import os, sys
sys.path.append(f'{os.path.dirname(sys.argv[0])}/../../lib')

from qemu import QemuConfig, qemu_main, qemu_monitor_shutdown
from utils import setup_logging


def main():
    setup_logging()

    qconf = QemuConfig('bamboo')
    qconf.configure_from_env()
    qconf.configure_from_args(sys.argv[1:])
    qconf.smp = 1

    def shutdown(p):
        p.send('poweroff')
        p.expect('System Halted, OK to turn off power')
        qemu_monitor_shutdown(p)

    qconf.shutdown = shutdown

    qconf.apply_defaults()

    return qemu_main(qconf)


sys.exit(0 if main() else 1)
