#!/usr/bin/python3
#
# $ export ROOT_DISK_PATH=~/root-disks/
# Expects ppc-rootfs.cpio.gz in ROOT_DISK_PATH
#
# $ cd ~/src/linux
# $ make
# $ ~/src/ci-scripts/scripts/boot/qemu-44x
#
# Or:
#
# export VMLINUX_PATH=~/src/linux/vmlinux
# export KERNEL_RELEASE_PATH=~/src/linux/include/config/kernel.release
#
# Optional:
# export QEMU_SYSTEM_PPC=~/src/qemu/ppc-softmmu/qemu-system-ppc

import logging
import os, sys
sys.path.append(f'{os.path.dirname(sys.argv[0])}/../../lib')

from qemu import qemu_command, qemu_net_setup
from pexpect_utils import *
from utils import *


def main():
    setup_logging()
    setup_timeout(60)

    if not check_env_vars(['ROOT_DISK_PATH']):
        return 1

    expected_release = get_expected_release()
    if expected_release is None:
        return False

    vmlinux = get_vmlinux()
    if vmlinux is None:
        return False

    p = PexpectHelper()
    cmd = qemu_command(qemu='qemu-system-ppc', machine='bamboo', vmlinux=vmlinux,
                       rootfs='ppc-rootfs.cpio.gz', cmdline='noreboot')
    p.spawn(cmd, logfile=open('console.log', 'w'))

    standard_boot(p)

    p.send("echo -n 'booted-revision: '; uname -r")
    p.expect(f'booted-revision: {expected_release}')
    p.expect_prompt()

    p.send('cat /proc/cpuinfo')
    p.expect("PowerPC 44x Platform")
    p.expect_prompt()

    qemu_net_setup(p)
    ping_test(p, check=False)
    wget_test(p)

    p.send('echo o > /proc/sysrq-trigger')
    p.expect('System Halted, OK to turn off power')

    p.terminate()

    if filter_log_warnings(open('console.log'), open('warnings.txt', 'w')):
        logging.error('Errors/warnings seen in console.log')
        return False

    logging.info('Test completed OK')

    return True


sys.exit(0 if main() else 1)
