#!/usr/bin/python3
#
# $ cd ~/src/linux
# $ make
# $ ~/src/ci-scripts/scripts/boot/qemu-powernv
#
# Or:
#
# export VMLINUX_PATH=~/src/linux/vmlinux
# export KERNEL_RELEASE_PATH=~/src/linux/include/config/kernel.release
#
# Optional:
# export QEMU_SYSTEM_PPC64=~/src/qemu/ppc64-softmmu/qemu-system-ppc64
#
# export CPU=(POWER8|POWER9)    # Default POWER8
# export ACCEL=(tcg|kvm)        # Default tcg
# export SMP=n                  # Default 2 for tcg or 8 for kvm
#
# export ROOT_DISK_PATH=~/some/directory
# Expects ppc64[le]-rootfs.cpio.gz in ROOT_DISK_PATH

import os, sys
sys.path.append(f'{os.path.dirname(sys.argv[0])}/../../lib')

from qemu import qemu_main
from utils import setup_logging, get_env_var


def main():
    setup_logging()

    cpu = get_env_var('CPU', 'POWER8')
    if cpu == 'POWER8':
        machine = 'powernv8'
    else:
        machine = 'powernv9'

    return qemu_main(machine, 'IBM PowerNV \(emulated by qemu\)', cpu,
                     net='-netdev user,id=net0 -device e1000e,netdev=net0',
                     args=sys.argv[1:])

sys.exit(0 if main() else 1)
