#!/bin/bash
#
# $ make pmac32_defconfig
# $ make guest.config
# $ echo CONFIG_CGROUPS=y >> .config
# $ echo CONFIG_DEVTMPFS=y >> .config
# $ make olddefconfig

exec "$(dirname "$0")"/qemu-mac99 --cloud-image debian-sid-powerpc.qcow2 "$@"
