#!/usr/bin/python3
#
# Kernel needs:
#   corenet32_smp_defconfig +
#   CONFIG_PPC_QEMU_E500=y
#   CONFIG_POWER_RESET_GPIO=y
#
# $ cd ~/src/linux
# $ make
# $ ~/src/ci-scripts/scripts/boot/qemu-e500mc
#
# Or:
#
# export VMLINUX_PATH=~/src/linux/vmlinux
# export KERNEL_RELEASE_PATH=~/src/linux/include/config/kernel.release
#
# Optional:
# export QEMU_SYSTEM_PPC=~/src/qemu/ppc-softmmu/qemu-system-ppc
# export ROOT_DISK_PATH=~/some/directory
#
# Expects ROOT_DISK_PATH to contain:
#   ppc-rootfs.cpio.gz

import logging
import os, sys
sys.path.append(f'{os.path.dirname(sys.argv[0])}/../../lib')

from qemu import QemuConfig, qemu_main
from utils import setup_logging


def main():
    setup_logging()

    qconf = QemuConfig('ppce500')
    qconf.configure_from_env()
    qconf.configure_from_args(sys.argv[1:])
    qconf.qemu_path = 'qemu-system-ppc'
    qconf.mem = '2G'
    qconf.smp = 1
    qconf.cpu = 'e500mc'

    qconf.apply_defaults()

    return qemu_main(qconf)

sys.exit(0 if main() else 1)
