#!/usr/bin/python3
#
# Kernel needs:
#   CONFIG_PPC_QEMU_E500=y
#   CONFIG_POWER_RESET_GPIO=y
#
# $ cd ~/src/linux
# $ make
# $ ~/src/ci-scripts/scripts/boot/qemu-ppc64e
#
# Optional:
# export ROOT_DISK_PATH=~/some/directory
#
# Expects ROOT_DISK_PATH to contain either:
#   ppc64-novsx-rootfs.cpio.gz
# or
#   ppc-rootfs.cpio.gz
#
# if --compat-rootfs is specified.

import logging
import os, sys
sys.path.append(f'{os.path.dirname(sys.argv[0])}/../../lib')

from qemu import QemuConfig, qemu_main
from utils import setup_logging


def main():
    setup_logging()

    qconf = QemuConfig('ppce500')
    qconf.cpu = 'e5500'
    qconf.configure_from_env()
    qconf.configure_from_args(sys.argv[1:])
    qconf.qemu_cmd = 'qemu-system-ppc64'
    qconf.mem = '4G'
    qconf.smp = 2

    qconf.apply_defaults()

    return qemu_main(qconf)

sys.exit(0 if main() else 1)
