#!/usr/bin/python3
#
# $ cd ~/src/linux
# $ make
# $ ~/src/ci-scripts/scripts/boot/qemu-powernv

import os, sys
sys.path.append(f'{os.path.dirname(sys.argv[0])}/../../lib')

from qemu import QemuConfig, qemu_main
from utils import setup_logging


def main():
    setup_logging()

    qconf = QemuConfig('powernv')
    qconf.net_tests = True
    qconf.configure_from_env()
    qconf.configure_from_args(sys.argv[1:])
    qconf.apply_defaults()

    return qemu_main(qconf)

sys.exit(0 if main() else 1)
