#!/usr/bin/python3
#
# Kernel needs:
#  CONFIG_SERIAL_PMACZILOG=y
#  CONFIG_SERIAL_PMACZILOG_TTYS=y
#  CONFIG_SERIAL_PMACZILOG_CONSOLE=y
#  CONFIG_DEVTMPFS=y
#  CONFIG_DEVTMPFS_MOUNT=y
#
# $ cd ~/src/linux
# $ make
# $ ~/src/ci-scripts/scripts/boot/qemu-mac99

import logging
import os, sys
sys.path.append(f'{os.path.dirname(sys.argv[0])}/../../lib')

from qemu import QemuConfig, qemu_main
from utils import setup_logging


def main():
    setup_logging()

    qconf = QemuConfig('mac99')
    qconf.configure_from_env()
    qconf.configure_from_args(sys.argv[1:])
    qconf.smp = 1
    qconf.apply_defaults()

    return qemu_main(qconf)


sys.exit(0 if main() else 1)
